[package]
name = "roundabout_sim"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
approx = "0.5.1"
json = "0.12.4"
macroquad = "0.4.14"
num-complex = "0.4.6"
ordered-float = "5.1.0"
rand = "0.9.2"
